# Generated by Django 5.1.5 on 2025-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
