# Generated by Django 5.1.5 on 2025-06-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_project_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PB', 'Published'), ('DF', 'Draft')], default='DF', max_length=2),
        ),
    ]
